# Generated by Django 5.0.1 on 2024-01-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheatreDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TheatreName', models.CharField(blank=True, max_length=100, null=True)),
                ('TheatreAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact', models.IntegerField(blank=True, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Screen', models.IntegerField(blank=True, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('TheatreImage', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
