# Generated by Django 5.0.1 on 2024-01-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theatre', models.CharField(blank=True, max_length=100, null=True)),
                ('ScreenName', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalSeat', models.IntegerField(blank=True, null=True)),
                ('PremiumSeat', models.IntegerField(blank=True, null=True)),
                ('StandardSeat', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
