# Generated by Django 5.0.1 on 2024-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_screendb'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovieName', models.CharField(blank=True, max_length=100, null=True)),
                ('Synopsis', models.CharField(blank=True, max_length=100, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('ReleaseDate', models.DateField(blank=True, null=True)),
                ('Poster1', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Poster2', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Poster3', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('TrailerLink', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
