# Generated by Django 5.0.1 on 2024-01-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_moviedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actor1Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor1Character', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor1Image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Actor2Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor2Character', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor2Image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Actor3Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor3Character', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor3Image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Actor4Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor4Character', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor4Image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('Actor5Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor5Character', models.CharField(blank=True, max_length=100, null=True)),
                ('Actor5Image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
    ]
