# Generated by Django 5.0.1 on 2024-01-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_castdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='castdb',
            name='Movie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
