# Generated by Django 5.0.1 on 2024-01-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_castdb_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastCrewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.CharField(blank=True, max_length=100, null=True)),
                ('ActorName', models.CharField(blank=True, max_length=100, null=True)),
                ('Character', models.CharField(blank=True, max_length=100, null=True)),
                ('ActorImage', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('CrewName', models.CharField(blank=True, max_length=100, null=True)),
                ('Role', models.CharField(blank=True, max_length=100, null=True)),
                ('CrewImage', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.DeleteModel(
            name='CastDB',
        ),
    ]
