# Generated by Django 5.0.1 on 2024-01-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_castcrewdb_delete_castdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castcrewdb',
            name='CrewImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
