# Generated by Django 5.0.1 on 2024-02-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_showtimedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theatre', models.CharField(blank=True, max_length=100, null=True)),
                ('Show', models.CharField(blank=True, max_length=100, null=True)),
                ('Movie', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.DateTimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
