# Generated by Django 5.0.1 on 2024-02-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_showdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theatre_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_seat', models.IntegerField()),
                ('Available', models.IntegerField()),
            ],
        ),
    ]
