# Generated by Django 5.0.1 on 2024-02-20 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_seatdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showdb',
            old_name='Show',
            new_name='Show1',
        ),
        migrations.AddField(
            model_name='showdb',
            name='Show2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showdb',
            name='Show3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showdb',
            name='Show4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='showdb',
            name='Show5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
