# Generated by Django 5.0.1 on 2024-02-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdb',
            name='Email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
