# Generated by Django 5.0.1 on 2024-02-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0005_customuser_username_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
