# Generated by Django 5.0.1 on 2024-02-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0009_theatreslotdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSlotDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=100, null=True)),
                ('TheatreName', models.CharField(blank=True, max_length=100, null=True)),
                ('TheatreAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('MovieName', models.CharField(blank=True, max_length=100, null=True)),
                ('SeatNum', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.CharField(blank=True, max_length=100, null=True)),
                ('TotalPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
