# Generated by Django 5.0.1 on 2024-02-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0011_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_name', models.CharField(blank=True, max_length=100, null=True)),
                ('theatre_name', models.CharField(blank=True, max_length=100, null=True)),
                ('theatre_address', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_seats', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_date', models.CharField(blank=True, max_length=100, null=True)),
                ('selected_time', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_status', models.BooleanField(default=False)),
                ('booked_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
